In [1]:
import pandas as pd 
import numpy as np

#read in all the data from directory 'all_appends_and_source' and store each in a dataframe 
# df_agr_email_cell = pd.read_csv('all_appends_and_source/agr_CF_CELL_EMAIL_22K_20220822.csv') # need to decided how we want to go about working with this file
df_agr_data_append = pd.read_csv('../Data/cf_AgrAppendedData_22k_6-21-2022.csv')
df_appriss_data_append = pd.read_csv('../Data/Cf_appenedToAprrissDataSample_8-18-2022.csv')
df_dev_sample_old = pd.read_csv('../Data/cf_DataSample_22k_8-8-2022.csv')
df_acxiom_append = pd.read_csv('../Data/cf_sampleforAcxiom_22k_6-20-2022_OUT.csv')
df_medial_source = pd.read_csv('../Data/CF_medicalData.csv')
df_10krando_source = pd.read_csv('../Data/AGR_OK_18PLUS_DOB_SAMPLE_10000_20220614.csv')



C:\Users\cayde\AppData\Local\Temp\ipykernel_11620\2180790063.py:6: DtypeWarning: Columns (13,67) have mixed types. Specify dtype option on import or set low_memory=False.
  df_agr_data_append = pd.read_csv('../Data/cf_AgrAppendedData_22k_6-21-2022.csv')
C:\Users\cayde\AppData\Local\Temp\ipykernel_11620\2180790063.py:7: DtypeWarning: Columns (25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df_appriss_data_append = pd.read_csv('../Data/Cf_appenedToAprrissDataSample_8-18-2022.csv')
C:\Users\cayde\AppData\Local\Temp\ipykernel_11620\2180790063.py:11: DtypeWarning: Columns (15,16,17,18,19,20,21,22,33,35,48,49,50,51,52,53,54,55,56,57,58,59,61,62,63,73,74,75,77,78,79,84,86,87,88,89,90,91,92,96,97,98,107,122,123) have mixed types. Specify dtype option on import or set low_memory=False.
  df_medial_source = pd.read_csv('../Data/CF_medicalData.csv')


In [2]:
#sanity check
# make sure we can the columns we are using in dev sample to cross check the dataframes yeild unqiue rows
#make a subset of the dev sample dataframe with the columns first and last name and address and city and state
df_dev_sample_sub = df_dev_sample[['FIRST_NAME','LAST_NAME','ADDRESS','CITY','STATE']]
#check to see that all rows are unquie in the dev sample and store all duplicates in a dataframe
dups_devsamp = df_dev_sample_sub[df_dev_sample_sub.duplicated(keep=False)]
# there is one example of a duplicate row in the dev sample so we will handle it manually
# dups name is howard meeks there are two of with matching columns they but the birthdays differ
# both parts of dup are sourced from medial source file so we can handle it there



In [3]:
# #cut down the medical source file to only the columns we need
# #add a column to the medical source file called 'ind' and itterate from zero
# # df_medial_source['ind'] = np.arange(len(df_medial_source))
# df_medial_source_sub = df_medial_source[['FirstName','LastName','Address', 'City','State']]
# #drop all rows with all null values
# df_medial_source_sub = df_medial_source_sub.dropna(how='all')

# #print the number of duplicates in the medical source file and the 10k rando file
# print('number of duplicates in medical source file: ',df_medial_source_sub.duplicated().sum())
# #store all duplicates in a dataframe
# dups_med = df_medial_source_sub[df_medial_source_sub.duplicated(keep=False)]



In [4]:
#cut down the medical source file to only the columns we need
#add a column to the medical source file called 'ind' and itterate from zero
# df_medial_source['ind'] = np.arange(len(df_medial_source))
df_medial_source_sub = df_medial_source[['FirstName','LastName', 'Address', 'City','State']]
#drop all rows with all null values
df_medial_source_sub = df_medial_source_sub.dropna(how='all')
dups_med = df_medial_source_sub[df_medial_source_sub.duplicated(keep=False)]

#cut down the 10k rando file to only the columns we need
df_10krando_source_sub = df_10krando_source[['FIRST_NAME','LAST_NAME','ADDRESS', 'CITY','STATE']]
df_10krando_source_sub = df_10krando_source_sub.dropna(how='all')
dups_randos = df_10krando_source_sub[df_10krando_source_sub.duplicated(keep=False)]

#print the number of duplicates in the medical source file and the 10k rando file
print('number of duplicates in medical source file: ',df_medial_source_sub.duplicated().sum())
print('number of duplicates in 10k rando file: ',df_10krando_source_sub.duplicated().sum())


#combine the two dataframes into one
# df_medial_and_10krando = df_medial_source_sub.append(df_10krando_source_sub, ignore_index=True)
# #print the number of duplicates in the combined dataframe
# print('number of duplicates in combined medical and 10k rando file: ',df_medial_and_10krando.duplicated().sum())



number of duplicates in medical source file:  0
number of duplicates in 10k rando file:  0


In [5]:
#change the names of the columns to match the names in the dev sample
df_medial_source_sub.columns = ['FIRST_NAME', 'LAST_NAME', 'ADDRESS', 'CITY', 'STATE']
#add a new column called source and fill it with the string 'medial_source'
df_medial_source_sub['source'] = 'medial_source'
#add a new column called source_ind and fill it with dataframes index
df_medial_source_sub['source_ind'] = df_medial_source_sub.index
#add a new column called source and fill it with the string '10krando_source'
df_10krando_source_sub['source'] = '10krando_source'
#add a new column called source_ind and fill it with dataframes index
df_10krando_source_sub['source_ind'] = df_10krando_source_sub.index

#combine the medical and 10k rando dataframes
df_medial_and_10krando = pd.concat([df_medial_source_sub, df_10krando_source_sub], ignore_index=True)
#order the dataframe by first name and last name and address and city and state
df_medial_and_10krando = df_medial_and_10krando.sort_values(by=['FIRST_NAME', 'LAST_NAME', 'ADDRESS', 'CITY', 'STATE'])

#append a new column to the dataframe called 'ind' and itterate from zero
df_medial_and_10krando['ind'] = np.arange(len(df_medial_and_10krando))

#order the dev sample by first name and last name and address and city and state
df_dev_sample = df_dev_sample.sort_values(by=['FIRST_NAME', 'LAST_NAME', 'ADDRESS', 'CITY', 'STATE'])

In [6]:
#merge the two dataframes on first name and last name and address and city and state
df_dev_sample = pd.merge(df_dev_sample, df_medial_and_10krando, on=['FIRST_NAME', 'LAST_NAME', 'CITY', 'STATE'], how='left')

#make a subset of this dataframe will all the rows that have missing values in the source column
dev_missing_source = df_dev_sample[df_dev_sample['source'].isnull()]





In [11]:
sanity = df_dev_sample[['source','source_ind']]
sanity = sanity.dropna(how='all')
sanity = sanity[sanity.duplicated(keep=False)]

In [10]:
#make a subset of the dev sample dataframe with the columns first and last name and address and city and state
dev_missing_source_sub = dev_missing_source[['FIRST_NAME','LAST_NAME','ADDRESS_x','CITY']]

#print the number of duplicates in the dev sample
print('number of duplicates in dev sample: ',dev_missing_source_sub.duplicated().sum())

number of duplicates in dev sample:  0


In [8]:
#add a column to both medial sub and 10k rando sub dataframes called ind 
df_10krando_source_sub['ind'] = np.arange(len(df_10krando_source_sub))

C:\Users\cayde\AppData\Local\Temp\ipykernel_17564\2685437121.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_10krando_source_sub['ind'] = np.arange(len(df_10krando_source_sub))


In [9]:

# #sanity check and proof of concept

# #grab the first 1000 entires from the dev sample
# df_dev_sample_sub_1000 = df_dev_sample_sub.head(10)

# # something funky is going on with addresses between med and dev_smaple
# # check to see if we have dev sample on big computer that has the matching dates
# # row:  ['.WILLIAM' 'MEEKS, II' '3209 S OWASSO AVE' 'TULSA' 'OK']
# # row_med:  ['.WILLIAM' 'MEEKS, II' '3209 SOUTH OWASSO AVENUE' 'TULSA' 'OK']


# for index, row in df_dev_sample_sub_1000.iterrows():
#     r1 = row.values
#     #check if this row is present in medical source sub
#     for ind_1, row_med in df_medial_source_sub.iterrows():
#         # print('row: ',row.values)
#         # print('row_med: ',row_med.values[0:5])
#         #remove 3rd element and store the rest in a variable
#         r2 = row_med.values[0:5]
#         r2 = np.delete(r2, 2)
#         r1_wo3 = np.delete(r1, 2)
#         if np.array_equal(r1_wo3,r2):
#             print('found match in medical source sub')
#             #if it is then add the ind from the medical source sub to the dev sample
#             df_dev_sample_sub_1000.loc[index,'Source'] = 'medical_source_index_' + str(row_med['ind'])
#             continue
#     for ind_2, row_rand in df_10krando_source_sub.iterrows():
#         # print('row: ',row.values)
#         # print('row_med: ',row_med.values[0:5])
#         r2 = row_rand.values[0:5]
#         if np.array_equal(r1,r2):
#             print('found match in random source sub')
#             #if it is then add the ind from the medical source sub to the dev sample
#             df_dev_sample_sub_1000.loc[index,'Source'] = 'random_sample_index_' + str(row_rand['ind'])
#             continue
    
    

In [16]:
array_med = df_medial_source_sub.values[:,0:5]
array_med = np.delete(array_med, 2, 1)

array_rando = df_10krando_source_sub.values[:,0:5]

In [22]:
#cut down the df_dev_sample_sub to only 100 rows
df_dev_sample_sub_100 = df_dev_sample_sub.head(100)

array_med = df_medial_source_sub.values[:,0:5]
array_med = np.delete(array_med, 2, 1)

array_rando = df_10krando_source_sub.values[:,0:5]

for index, row in df_dev_sample_sub.iterrows():
    print('row: ',row.values)
    if row.values in array_med:
        print('found match in medical source sub')
        #if it is then add the ind from the medical source sub to the dev sample
        df_dev_sample_sub_100.loc[index,'Source'] = 'medical_source_index_' + str(df_medial_source_sub.loc[df_medial_source_sub.values == row.values].index[0])
        continue
    if row.values in array_rando:
        print('found match in random source sub')
        #if it is then add the ind from the medical source sub to the dev sample
        df_dev_sample_sub_100.loc[index,'Source'] = 'random_sample_index_' + str(df_10krando_source_sub.loc[df_10krando_source_sub.values == row.values].index[0])
        continue


row:  ['.WILLIAM' 'MEEKS, II' '3209 S OWASSO AVE' 'TULSA' 'OK']


C:\Users\cayde\AppData\Local\Temp\ipykernel_17564\3695915755.py:11: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  print(str(df_medial_source_sub[df_medial_source_sub.values == row.values]))


KeyError: False

In [23]:
for index, row in df_dev_sample_sub.iterrows():
    ii = np.where(array_med == row.values)[0]
    print(ii)
    ii_2 = np.where(array_rando == row.values)[0]
    print(ii_2)


C:\Users\cayde\AppData\Local\Temp\ipykernel_17564\2790638468.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  ii = np.where(array_med == row.values)[0]


[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    0    0 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    0    1 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    0    1 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 ... 9997 9998 9999]
[]
[   0    1    2 

KeyboardInterrupt: 

In [10]:
for index, row in df_dev_sample_sub.iterrows():
    r1 = row.values
    #check if this row is present in medical source sub
    for ind_1, row_med in df_medial_source_sub.iterrows():
        #remove 3rd element and store the rest in a variable
        r2 = row_med.values[0:5]
        r2 = np.delete(r2, 2)
        r1_wo3 = np.delete(r1, 2)
        if np.array_equal(r1_wo3,r2):
            #if it is then add the ind from the medical source sub to the dev sample
            df_dev_sample.loc[index,'Source'] = 'medical_source_index_' + str(row_med['ind'])
            continue
    for ind_2, row_rand in df_10krando_source_sub.iterrows():
        r2 = row_rand.values[0:5]
        if np.array_equal(r1,r2):
            #if it is then add the ind from the medical source sub to the dev sample
            df_dev_sample.loc[index,'Source'] = 'random_sample_index_' + str(row_rand['ind'])
            continue

KeyboardInterrupt: 

In [ ]:
#write the dev sample to a csv
df_dev_sample.to_csv('../data/dev_sample_with_source.csv', index=False)

In [ ]:
#convert all na's in the source column to 'not_found'
df_dev_sample['SOURCE'] = df_dev_sample['SOURCE'].fillna('not_found')
#count the number of rows in the dev sample dataframe that have a source of not_found
print('number of rows in dev sample with source of not_found: ',df_dev_sample[df_dev_sample['SOURCE'] == 'not_found'].shape[0])
#count the number of rows in the dev sample that have the source column containing 'random_sample_index'
print('number of rows in dev sample with source column containing random_sample_index: ',df_dev_sample[df_dev_sample['SOURCE'].str.contains('random_sample_index')].shape[0])
#count the number of rows in the dev sample that have the source column containing 'medial_source_index'
print('number of rows in dev sample with source column containing medial_source_index: ',df_dev_sample[df_dev_sample['SOURCE'].str.contains('random_medical')].shape[0])
